// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSJvE-YczrKPtluFbFqdBrHjIYSE7_Xas',
    appId: '1:406749288153:web:1659dd126d412900fdd0c8',
    messagingSenderId: '406749288153',
    projectId: 'onlineclass-3ff52',
    authDomain: 'onlineclass-3ff52.firebaseapp.com',
    storageBucket: 'onlineclass-3ff52.firebasestorage.app',
    measurementId: 'G-WW013GB355',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdFdPbVz-BGyAjeBNlasP4-IimW9yF550',
    appId: '1:406749288153:android:783678a908ec9bd8fdd0c8',
    messagingSenderId: '406749288153',
    projectId: 'onlineclass-3ff52',
    storageBucket: 'onlineclass-3ff52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA360vd58Cng3JD2v4RNvoA51FauKA-_tA',
    appId: '1:406749288153:ios:418f757b328dd417fdd0c8',
    messagingSenderId: '406749288153',
    projectId: 'onlineclass-3ff52',
    storageBucket: 'onlineclass-3ff52.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA360vd58Cng3JD2v4RNvoA51FauKA-_tA',
    appId: '1:406749288153:ios:418f757b328dd417fdd0c8',
    messagingSenderId: '406749288153',
    projectId: 'onlineclass-3ff52',
    storageBucket: 'onlineclass-3ff52.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSJvE-YczrKPtluFbFqdBrHjIYSE7_Xas',
    appId: '1:406749288153:web:020b8a0114aefcc3fdd0c8',
    messagingSenderId: '406749288153',
    projectId: 'onlineclass-3ff52',
    authDomain: 'onlineclass-3ff52.firebaseapp.com',
    storageBucket: 'onlineclass-3ff52.firebasestorage.app',
    measurementId: 'G-QZGCTCHKMB',
  );
}
